/**
 * TEMP - FAKE DATA
 */
import {
  Media,
  Prisma,
  Vehicle,
  VehicleBrand,
  VehicleCondition,
} from "@prisma/client";

export const VEHICLE_MEDIA_LIST: Media[] = [
  {
    id: 1,
    url: "https://www.beamng.com/attachments/screenshot_2025-01-05_21-45-45-png.1196988/",
    is_thumbnail: true,
    vehicle: null,
    wheel: null,
    date_created: null,
  },
  {
    id: 2,
    url: "https://www.beamng.com/attachments/screenshot_2025-01-06_20-07-42-png.1196990/",
    is_thumbnail: false,
    vehicle: null,
    wheel: null,
    date_created: null,
  },
  {
    id: 3,
    url: "https://www.beamng.com/attachments/screenshot_2025-01-06_20-23-55-png.1196993/",
    is_thumbnail: false,
    vehicle: null,
    wheel: null,
    date_created: null,
  },
  {
    id: 4,
    url: "https://www.beamng.com/attachments/screenshot_2025-01-06_23-16-33-png.1196994/",
    is_thumbnail: false,
    vehicle: null,
    wheel: null,
    date_created: null,
  },
];

export const VEHICLE_LIST: Vehicle[] = [
  {
    id: 1,
    condition: VehicleCondition.USED,
    thumbnail_url:
      "https://preview.redd.it/i-need-a-new-daily-so-i-went-to-the-dealership-to-see-some-v0-yza8t3h9mbhb1.jpg?width=1920&format=pjpg&auto=webp&s=6c4d549f815c094ee15e9fbdd33c9716ba318f27",
    year: 2012,
    brand: VehicleBrand.ETK,
    model: "800 wagon",
    price_cts: BigInt(3299900),
    mileage: 14245,
    description: "",
    date_created: null,
    slug: "",
    country: "GERMANY",
    body_style: "PICKUP",
    weight_lbs: 1464,
    power_bhp: 232,
    zero_to_sixty_seconds: new Prisma.Decimal(9.9),
    top_speed_mph: 145,
    fuel_type: "GASOLINE",
    drivetrain: "RWD",
    transmission: "MANUAL",
  },
  {
    id: 2,
    condition: VehicleCondition.USED,
    thumbnail_url:
      "https://preview.redd.it/i-need-a-new-daily-so-i-went-to-the-dealership-to-see-some-v0-yza8t3h9mbhb1.jpg?width=1920&format=pjpg&auto=webp&s=6c4d549f815c094ee15e9fbdd33c9716ba318f27",
    year: 2012,
    brand: VehicleBrand.ETK,
    model: "800 wagon",
    price_cts: BigInt(3299900),
    mileage: 14245,
    description: "",
    date_created: null,
    slug: "",
    country: "GERMANY",
    body_style: "PICKUP",
    weight_lbs: 1464,
    power_bhp: 232,
    zero_to_sixty_seconds: new Prisma.Decimal(9.9),
    top_speed_mph: 145,
    fuel_type: "GASOLINE",
    drivetrain: "RWD",
    transmission: "MANUAL",
  },
  {
    id: 3,
    condition: VehicleCondition.USED,
    thumbnail_url:
      "https://preview.redd.it/i-need-a-new-daily-so-i-went-to-the-dealership-to-see-some-v0-yza8t3h9mbhb1.jpg?width=1920&format=pjpg&auto=webp&s=6c4d549f815c094ee15e9fbdd33c9716ba318f27",
    year: 2012,
    brand: VehicleBrand.ETK,
    model: "800 wagon",
    price_cts: BigInt(3299900),
    mileage: 14245,
    description: "",
    date_created: null,
    slug: "",
    country: "GERMANY",
    body_style: "PICKUP",
    weight_lbs: 1464,
    power_bhp: 232,
    zero_to_sixty_seconds: new Prisma.Decimal(9.9),
    top_speed_mph: 145,
    fuel_type: "GASOLINE",
    drivetrain: "RWD",
    transmission: "MANUAL",
  },
  {
    id: 4,
    condition: VehicleCondition.USED,
    thumbnail_url:
      "https://preview.redd.it/i-need-a-new-daily-so-i-went-to-the-dealership-to-see-some-v0-yza8t3h9mbhb1.jpg?width=1920&format=pjpg&auto=webp&s=6c4d549f815c094ee15e9fbdd33c9716ba318f27",
    year: 2012,
    brand: VehicleBrand.ETK,
    model: "800 wagon",
    price_cts: BigInt(3299900),
    mileage: 14245,
    description: "",
    date_created: null,
    slug: "",
    country: "GERMANY",
    body_style: "PICKUP",
    weight_lbs: 1464,
    power_bhp: 232,
    zero_to_sixty_seconds: new Prisma.Decimal(9.9),
    top_speed_mph: 145,
    fuel_type: "GASOLINE",
    drivetrain: "RWD",
    transmission: "MANUAL",
  },
  {
    id: 5,
    condition: VehicleCondition.USED,
    thumbnail_url:
      "https://preview.redd.it/i-need-a-new-daily-so-i-went-to-the-dealership-to-see-some-v0-yza8t3h9mbhb1.jpg?width=1920&format=pjpg&auto=webp&s=6c4d549f815c094ee15e9fbdd33c9716ba318f27",
    year: 2012,
    brand: VehicleBrand.ETK,
    model: "800 wagon",
    price_cts: BigInt(3299900),
    mileage: 14245,
    description: "",
    date_created: null,
    slug: "",
    country: "GERMANY",
    body_style: "PICKUP",
    weight_lbs: 1464,
    power_bhp: 232,
    zero_to_sixty_seconds: new Prisma.Decimal(9.9),
    top_speed_mph: 145,
    fuel_type: "GASOLINE",
    drivetrain: "RWD",
    transmission: "MANUAL",
  },
];
